name: MediaPlayerKitDemo
options:
  bundleIdPrefix: com.yuanyuanhui
  xcodeVersion: "15.0"
  defaultConfig: Release
  deploymentTarget:
    iOS: "14.0"
    macOS: "11.0"
packages:
  KSPlayer:
    url: https://github.com/kingslay/KSPlayer.git
    from: 2.3.4
targets:
  MediaPlayerKit:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: 
      - path: Sources/MediaPlayerKit
    dependencies:
      - package: KSPlayer
        product: KSPlayer
    info:
      path: Sources/MediaPlayerKit/Info.plist
    settings:
      base:
        PRODUCT_NAME: MediaPlayerKit
        PRODUCT_BUNDLE_IDENTIFIER: com.yuanyuanhui.MediaPlayerKit
        SWIFT_VERSION: "5.9"
        ENABLE_BITCODE: NO

  MediaPlayerKitDemo:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Examples/MediaPlayerKitDemo
    dependencies:
      - target: MediaPlayerKit
    info:
      path: Examples/MediaPlayerKitDemo/Info.plist
    settings:
      base:
        PRODUCT_NAME: MediaPlayerKitDemo
        PRODUCT_BUNDLE_IDENTIFIER: com.yuanyuanhui.MediaPlayerKitDemo
        DEVELOPMENT_TEAM: GB8FE8WWF8
        CODE_SIGN_STYLE: Manual
        SWIFT_VERSION: "5.9"
        ENABLE_BITCODE: NO
