// Generated by scripts/generate_versions.py; do not edit.
public enum SDKVersion {
    public static let releaseVersion = "1.0.0"
    public static let version = "1.0.0+development"
    public static let buildDate = "development"
    public static let buildNumber = "0"
    public static let commit = "development"
    public static let isDevelopment = true
}
