#!/usr/bin/env python3
"""Generate version artifacts from SDK_VERSION / DEMO_VERSION. No network or git mutation."""
import argparse
import json
import re
import subprocess
from datetime import datetime, timezone, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

BEIJING_TIME = timezone(timedelta(hours=8))

def build_timestamp(now=None):
    return (now or datetime.now(BEIJING_TIME)).astimezone(BEIJING_TIME).strftime('%Y%m%d%H%M%S(UTC+8)')

def full_version(version, build_number, commit, build_date):
    if build_date == 'development':
        return version + '+development'
    return f'{version}+{build_date}.{commit[:12]}.{build_number}'

def outputs(root, build_number='0', commit='development', release_tag=None, build_date='development'):
    versions = {name: (root / name).read_text().strip() for name in ('SDK_VERSION', 'DEMO_VERSION')}
    for name, value in versions.items():
        if not re.fullmatch(r'(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)', value):
            raise ValueError(f'{name}: expected major.minor.patch without leading zeros')
    if not re.fullmatch(r'0|[1-9]\d*', build_number):
        raise ValueError('build number must be a nonnegative integer')
    if commit != 'development' and not re.fullmatch(r'[0-9a-f]{7,40}', commit):
        raise ValueError('commit must be a lowercase Git hash or development')
    if build_date != 'development':
        if not re.fullmatch(r'\d{14}\(UTC\+8\)', build_date):
            raise ValueError('build date must be Beijing time (UTC+8) YYYYMMDDHHMMSS(UTC+8)')
        datetime.strptime(build_date, '%Y%m%d%H%M%S(UTC+8)')
        if commit == 'development':
            raise ValueError('dated build requires a Git commit')
    sdk, demo = versions['SDK_VERSION'], versions['DEMO_VERSION']
    if release_tag is not None and release_tag != 'v' + sdk:
        raise ValueError(f'release tag must be v{sdk}')
    if release_tag is not None and (build_number == '0' or commit == 'development' or build_date == 'development'):
        raise ValueError('release requires a CI build number, Git commit and build date')
    def swift(name, version):
        return ('// Generated by scripts/generate_versions.py; do not edit.\n'
                f'public enum {name} {{\n'
                f'    public static let releaseVersion = "{version}"\n'
                f'    public static let version = "{full_version(version, build_number, commit, build_date)}"\n'
                f'    public static let buildDate = "{build_date}"\n'
                f'    public static let buildNumber = "{build_number}"\n'
                f'    public static let commit = "{commit}"\n'
                f'    public static let isDevelopment = {str(build_number == "0").lower()}\n'
                '}\n')
    return {
        'Sources/MediaPlayerKit/API/SDKVersion.swift': swift('SDKVersion', sdk),
        'Examples/MediaPlayerKitDemo/DemoVersion.swift': swift('DemoVersion', demo),
        'Config/Versions.xcconfig': '// Generated by scripts/generate_versions.py; do not edit.\n'
            f'MPK_SDK_VERSION = {sdk}\nMPK_DEMO_VERSION = {demo}\nCURRENT_PROJECT_VERSION = {build_number}\n',
    }

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--build', action='store_true', help='stamp current Beijing time (UTC+8) and local Git HEAD')
    parser.add_argument('--build-date')
    parser.add_argument('--build-number', default='0')
    parser.add_argument('--commit', default='development')
    parser.add_argument('--release-tag')
    parser.add_argument('--manifest', type=Path)
    args = parser.parse_args()
    try:
        if args.build:
            if args.check: raise ValueError('--build cannot be combined with --check')
            if args.commit == 'development':
                args.commit = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip()
        if args.build_date is None:
            args.build_date = build_timestamp() if args.commit != 'development' else 'development'
        if args.check and args.manifest:
            raise ValueError("--manifest cannot be used with --check")
        files = outputs(ROOT, args.build_number, args.commit, args.release_tag, args.build_date)
        mismatches = []
        for path, content in files.items():
            target = ROOT / path
            if args.check:
                if not target.exists() or target.read_text() != content:
                    mismatches.append(path)
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content)
        if mismatches:
            raise ValueError('stale generated files: ' + ', '.join(mismatches))
        if args.manifest:
            args.manifest.parent.mkdir(parents=True, exist_ok=True)
            args.manifest.write_text(json.dumps({
                'sdkVersion': (ROOT / 'SDK_VERSION').read_text().strip(),
                'demoVersion': (ROOT / 'DEMO_VERSION').read_text().strip(),
                'buildNumber': args.build_number, 'commit': args.commit,
                'buildDate': args.build_date,
                'sdkBuildVersion': full_version((ROOT / 'SDK_VERSION').read_text().strip(), args.build_number, args.commit, args.build_date),
                'demoBuildVersion': full_version((ROOT / 'DEMO_VERSION').read_text().strip(), args.build_number, args.commit, args.build_date),
                'releaseTag': args.release_tag,
            }, indent=2) + '\n')
    except ValueError as error:
        parser.error(str(error))

if __name__ == '__main__':
    main()
