const {readFileSync} = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = readFileSync(require('node:path').join(__dirname, '../../Sources/MediaPlayerKit/Resources/vzplayer-bridge.js'), 'utf8');
const code = source;
function setup(native) {
    const messages = [], timers = new Map(), events = {};
    let sequence = 0;
    const window = {vzPlayerBridge: {}, addEventListener: (name, fn) => events[name] = fn};
    if (native) window.AndroidBridge = native;
    else window.webkit = {messageHandlers: {vzPlayerBridge: {postMessage: msg => messages.push(msg)}}};
    const context = vm.createContext({window, setTimeout: fn => { timers.set(++sequence, fn); return sequence; }, clearTimeout: id => timers.delete(id)});
    vm.runInContext(code, context);
    if (!native) {
        const hello = messages.shift();
        assert.equal(hello.method, 'bridgeReady');
        assert.equal(hello.pageId, window.vzPlayerBridge.pageId);
    }
    return {bridge: window.vzPlayerBridge, messages, timers, events, reinstall: () => vm.runInContext(code, context)};
}
(async () => {
    const statisticsNative = setup({get_statistics: () => JSON.stringify({sessionId: 's', session: {play_ms: 1200}})});
    const statistics = await statisticsNative.bridge.request('getStatistics');
    assert.equal(statistics.sessionId, 's');
    assert.equal(statistics.session.play_ms, 1200);
    assert.equal(await statisticsNative.bridge.ready(), null);
    const ios = setup();
    const ready = ios.bridge.ready();
    const handshake = ios.messages.pop();
    assert.equal(handshake.method, 'bridgeReady');
    assert.equal(handshake.pageId, ios.bridge.pageId);
    ios.bridge.onResponse({requestId: handshake.requestId, pageId: handshake.pageId, ok: true,
        result: {event: 'playing', currentTime: 12, muted: true}});
    assert.equal((await ready).currentTime, 12);
    const newPage = setup();
    assert.notEqual(newPage.bridge.pageId, ios.bridge.pageId);
    const isolated = newPage.bridge.request('getVolume');
    const newRequest = newPage.messages[0];
    assert.notEqual(newRequest.requestId, handshake.requestId);
    newPage.bridge.onResponse({requestId: newRequest.requestId, pageId: ios.bridge.pageId, ok: true, result: 'stale'});
    assert.equal(newPage.timers.size, 1);
    newPage.bridge.onResponse({requestId: newRequest.requestId, pageId: newPage.bridge.pageId, ok: true, result: 'fresh'});
    assert.equal(await isolated, 'fresh');
    const first = ios.bridge.request('getVolume');
    const request = ios.bridge.request;
    ios.reinstall();
    assert.equal(ios.bridge.request, request);
    const second = ios.bridge.request('setVolume', {volume: 2});
    ios.bridge.onResponse({requestId: ios.messages[1].requestId, ok: false, error: 'invalid_parameters_or_rejected'});
    await assert.rejects(second, /invalid_parameters/);
    ios.bridge.onResponse({requestId: ios.messages[0].requestId, ok: true, result: {volume: 0.5}});
    assert.equal((await first).volume, 0.5);
    assert.equal(ios.timers.size, 0);
    const timeout = ios.bridge.request('getVolume');
    [...ios.timers.values()][0]();
    await assert.rejects(timeout, /bridge_timeout/);
    const closed = ios.bridge.request('getVolume');
    ios.events.pagehide();
    await assert.rejects(closed, /page_closed/);
    await assert.rejects(ios.bridge.request('play'), /page_closed/);
    ios.events.pageshow();
    const restored = ios.bridge.ready();
    const restoreRequest = ios.messages.at(-1);
    ios.bridge.onResponse({requestId: restoreRequest.requestId, ok: true, result: {event:'pause'}});
    assert.equal((await restored).event, 'pause');
    const android = setup({get_volume: () => '{"volume":0.8}', set_volume: () => false});
    assert.equal((await android.bridge.request('getVolume')).volume, 0.8);
    await assert.rejects(android.bridge.request('setVolume', {volume: 2}), /invalid_parameters/);
    await assert.rejects(android.bridge.request('missing'), /unsupported_method/);
    await assert.rejects(android.bridge.request('SendEvent', {eventName:'NEXT_SOURCE'}), /android_event_adapter_required/);
    const calls = [];
    android.bridge.configure({androidSendEvent: (event, params) => { calls.push([event, JSON.parse(params)]); return true; }});
    assert.equal(await android.bridge.request('SendEvent', {eventName:'NEXT_SOURCE', params:{reason:'retry'}}), true);
    assert.deepEqual(calls, [['NEXT_SOURCE', {reason:'retry'}]]);
    await assert.rejects(android.bridge.request('SendEvent', {eventName:'SWITCH_SOURCE', params:{index:1}}), /unsupported_event/);
    await assert.rejects(android.bridge.request('SendEvent', {eventName:'NEXT_SOURCE', params:[]}), /invalid_parameters/);
    android.bridge.configure({androidSendEvent: () => false});
    await assert.rejects(android.bridge.request('SendEvent', {eventName:'NEXT_SOURCE'}), /invalid_parameters_or_rejected/);
    android.bridge.configure({androidSendEvent: async () => true});
    assert.equal(await android.bridge.request('SendEvent', {eventName:'SWITCH_PLAYER'}), true);
    ios.bridge.onResponse(null);
    console.log('Bridge tests passed: reply correlation, failure, timeout, page cleanup, Android aliases/results.');
})().catch(error => { console.error(error); process.exitCode = 1; });
